# Generated by Django 5.0.4 on 2024-05-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_item_out_of_stock_item_price_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
