databases:
  - name: florblancav2db
    plan: free
    region: frankfurt
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    region: frankfurt
    name: laflorblanca
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: florblancav2db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - fromGroup: flor_blanca_env
  
  - type: redis
  name: thunder
  plan: free
  region: frankfurt
  maxmemoryPolicy: allkeys-lru
  ipAllowList:
  - source: 80.5.141.61/32
    description: alex.landin@hotmail.com
version: "1"