databases:
  - name: florblancav2db
    plan: free
    region: frankfurt
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    name: laflorblanca
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn django_core.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: florblancav2db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - fromGroup: flor_blanca_env