# Generated by Django 5.0.4 on 2024-06-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_posts',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='members.post'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_videos',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='members.videolink'),
        ),
    ]
