# Generated by Django 5.0.4 on 2024-04-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_user_customer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
