# Generated by Django 5.0.4 on 2024-06-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_videolink_videoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolink',
            name='url',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
