# Generated by Django 5.0.4 on 2024-04-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_post_postrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('soul', 'Soul'), ('spirit', 'Spirit'), ('tarot', 'Tarot')], max_length=10)),
                ('url', models.URLField(max_length=350)),
                ('uploaded_on', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
