# Generated by Django 5.0.4 on 2024-04-23 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_posts',
            field=models.ManyToManyField(related_name='favorited_by', to='members.post'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_videos',
            field=models.ManyToManyField(related_name='favorited_by', to='members.videolink'),
        ),
        migrations.AlterField(
            model_name='user',
            name='customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
