# Generated by Django 5.0.4 on 2024-04-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_contentcategory_like_alter_post_title_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='comment'),
            preserve_default=False,
        ),
    ]
