# Generated by Django 5.0.4 on 2024-04-26 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_comment_post_alter_comment_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked_comment',
        ),
        migrations.RemoveField(
            model_name='like',
            name='liked_post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='liked_video',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
