# Generated by Django 5.0.4 on 2024-05-04 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_basicquestion_premiumquestion_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicquestion',
            name='info',
        ),
        migrations.AddField(
            model_name='basicquestion',
            name='age_group',
            field=models.CharField(default='20', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicquestion',
            name='city',
            field=models.CharField(default='London', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicquestion',
            name='country',
            field=models.CharField(default='Japan', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicquestion',
            name='gender',
            field=models.CharField(default='Female', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicquestion',
            name='media',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicquestion',
            name='subject',
            field=models.CharField(default='something', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='basic_used_questions',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='live_used_questions',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tarot_used_questions',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
    ]
