# Generated by Django 5.0.4 on 2024-05-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_alter_premiumquestion_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
