# Generated by Django 5.0.4 on 2024-05-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_alter_membership_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='subscription_id',
            field=models.CharField(default='tetstettsgdhfjfmfj', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
