# Generated by Django 5.0.4 on 2024-05-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_membership_subscription_id_alter_membership_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='subscription_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
